config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tops#index"
  resources :librarys
  resources :hindus
  resources :tops
  resources :opens
  resources :riffles
  resources :farrows
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library.rb
class Library < ApplicationRecord
  has_one_attached :image
  validates :card_type, presence: true
  validates :numbers, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth if Rails.env.production?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/farrows_controller.rb
class FarrowsController < ApplicationController
  before_action :farrow_shuffle, only: [:index]
  
  def index
   @farrow = Library.order("created_at DESC")
  end

  private

  def farrow_shuffle
    library_farrow_shuffle = Library.order("created_at DESC")
    farrow_1 = library_farrow_shuffle.last(rand(24..27))
    farrow_2 = library_farrow_shuffle - farrow_1
    farrow_3_0 = farrow_1.slice(0)
    farrow_2.insert(rand(0..1),farrow_3_0)
    farrow_3_1 = farrow_1.slice(1)
    farrow_2.insert(rand(2..3),farrow_3_1)
    farrow_3_2 = farrow_1.slice(2)
    farrow_2.insert(rand(4..5),farrow_3_2)
    farrow_3_3 = farrow_1.slice(3)
    farrow_2.insert(rand(6..7),farrow_3_3)
    farrow_3_4 = farrow_1.slice(4)
    farrow_2.insert(rand(8..9),farrow_3_4)
    farrow_3_5 = farrow_1.slice(5)
    farrow_2.insert(rand(10..11),farrow_3_5)
    farrow_3_6 = farrow_1.slice(6)
    farrow_2.insert(rand(12..13),farrow_3_6)
    farrow_3_7 = farrow_1.slice(7)
    farrow_2.insert(rand(14..15),farrow_3_7)
    farrow_3_8 = farrow_1.slice(8)
    farrow_2.insert(rand(16..17),farrow_3_8)
    farrow_3_9 = farrow_1.slice(9)
    farrow_2.insert(rand(18..19),farrow_3_9)
    farrow_3_10 = farrow_1.slice(10)
    farrow_2.insert(rand(20..21),farrow_3_10)
    farrow_3_11 = farrow_1.slice(11)
    farrow_2.insert(rand(22..23),farrow_3_11)
    farrow_3_12 = farrow_1.slice(12)
    farrow_2.insert(rand(24..25),farrow_3_12)
    farrow_3_13 = farrow_1.slice(13)
    farrow_2.insert(rand(26..27),farrow_3_13)
    farrow_3_14 = farrow_1.slice(14)
    farrow_2.insert(rand(28..29),farrow_3_14)
    farrow_3_15 = farrow_1.slice(15)
    farrow_2.insert(rand(30..31),farrow_3_15)
    farrow_3_16 = farrow_1.slice(16)
    farrow_2.insert(rand(32..33),farrow_3_16)
    farrow_3_17 = farrow_1.slice(17)
    farrow_2.insert(rand(34..35),farrow_3_17)
    farrow_3_18 = farrow_1.slice(18)
    farrow_2.insert(rand(36..37),farrow_3_18)
    farrow_3_19 = farrow_1.slice(19)
    farrow_2.insert(rand(38..39),farrow_3_19)
    farrow_3_20 = farrow_1.slice(20)
    farrow_2.insert(rand(40..41),farrow_3_20)
    farrow_3_21 = farrow_1.slice(21)
    farrow_2.insert(rand(42..43),farrow_3_21)
    farrow_3_22 = farrow_1.slice(22)
    farrow_2.insert(rand(44..45),farrow_3_22)
    farrow_3_23 = farrow_1.slice(23)
    farrow_2.insert(rand(46..47),farrow_3_23)
    farrow_3_24 = farrow_1.slice(24)
    farrow_2.insert(rand(48..49),farrow_3_24)
    farrow_3_25 = farrow_1.slice(25)
    farrow_2.insert(rand(50..51),farrow_3_25)
    farrow_3_26 = farrow_1.slice(26)
    farrow_2.insert(rand(52..53),farrow_3_26)
    @farrow_shuffle = farrow_2.compact
  end
end

app/controllers/hindus_controller.rb
class HindusController < ApplicationController
  before_action :library_hindu_shuffle, only: [:index, :show]
  
  def index
   @librarys = Library.order("created_at DESC")
  end
 
 
 
              private

             def library_hindu_shuffle
 
               library_hindu_shuffle = Library.order("created_at DESC")
               hindu_1 = library_hindu_shuffle.last(rand(27..52))
               hindu_2 = hindu_1 + (library_hindu_shuffle - hindu_1)
               hindu_3 = hindu_2.last(rand(27..52))
               hindu_4 = hindu_3 + (library_hindu_shuffle - hindu_3)
               hindu_5 = hindu_4.last(rand(27..53))
               hindu_6 = hindu_5 + (library_hindu_shuffle - hindu_5)
               hindu_7 = hindu_6.last(rand(27..53))
               hindu_8 = hindu_7 + (library_hindu_shuffle - hindu_7)
               hindu_9 = hindu_8.last(rand(27..53))
               hindu_10 = hindu_9 + (library_hindu_shuffle - hindu_9)
               hindu_11 = hindu_10.last(rand(27..53))
               hindu_12 = hindu_11 + (library_hindu_shuffle - hindu_11)
               hindu_13 = hindu_12.last(rand(27..53))
               hindu_14 = hindu_13 + (library_hindu_shuffle - hindu_13)
               hindu_15 = hindu_14.last(rand(27..53))
               hindu_16 = hindu_15 + (library_hindu_shuffle - hindu_15)
               hindu_17 = hindu_16.last(rand(27..53))
               hindu_18 = hindu_17 + (library_hindu_shuffle - hindu_17)
               hindu_19 = hindu_18.last(rand(27..53))
               hindu_20 = hindu_19 + (library_hindu_shuffle - hindu_19)
               @hindu_shuffle = hindu_20
             end
end

app/controllers/librarys_controller.rb
class LibrarysController < ApplicationController
  before_action :library_set, except: [:index, :new, :create, :show]
    before_action :library_rundam_all, only: [:index, :show]
    before_action :library_rundam_five, only: [:index, :show]
  
   def index
    @librarys = Library.order("created_at DESC")
   end
  
   def new
    @library = Library.new
   end
  
   def create
     @library = Library.new(library_params)
     if @library.save
       redirect_to root_path
     else
       render :new
     end
   end
   
   def show
    @librarys = Library.order("created_at DESC")
   end
  
   def edit
   end
  
   def update
    if @library.update(library_params)
      redirect_to library_path
    else
      render :edit
    end
   end
  
   def destroy
    if
     @library.destroy
     redirect_to root_path
    else
     redirect_to root_path
    end
   end
  
   private
                            def library_params
                              params.require(:library).permit(:card_type, :image, :numbers)
                            end
                
                            def library_set
                              @library = Library.find(params[:id])
                            end
                
                            def library_rundam_all
                              @library_rundam_all = Library.order("RAND()")
                            end
                
                            def library_rundam_five
                              @library_rundam_five = Library.order("RAND()").limit(5)
                            end
end

app/controllers/opens_controller.rb
class OpensController < ApplicationController
  def index
    @open = Library.all
  end
end

app/controllers/riffles_controller.rb
class RifflesController < ApplicationController
  before_action :riffle_shuffle, only: [:index]

  def index
   @riffle = Library.order("created_at DESC")
  end
  private

  def riffle_shuffle
    riffle = Library.order("created_at DESC")

    riffle_1 = riffle.last(rand(25..29))
    riffle_2 = riffle - riffle_1
    riffle_3 = riffle_1 + riffle_2
    riffle_3_1 = riffle_3[0,27].reverse
    riffle_3_2 = riffle_3[27,52].reverse
    riffle_4 = riffle_3_1.zip(riffle_3_2).flatten.compact
    riffle_4_1 = riffle_4[0,25].reverse
    riffle_4_2 = riffle_4[25,52].reverse
    @riffle_shuffle = riffle_4_1.zip(riffle_4_2).flatten.compact


  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  before_action :first_card, only: [:index]
  before_action :library_rundam_five, only: [:index, :show]
  def index
  end
  
  private

  def first_card
    all_card = Library.all
    @first_card = all_card.first(1)
  end

  def library_rundam_five
    @library_rundam_five = Library.order("RAND()").limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farrows_helper.rb
module FarrowsHelper
end

app/helpers/hindus_helper.rb
module HindusHelper
end

app/helpers/librarys_helper.rb
module LibrarysHelper
end

app/helpers/opens_helper.rb
module OpensHelper
end

app/helpers/riffles_helper.rb
module RifflesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/farrows/index.html.erb
<%= render "shared/header" %>
 <br>
 <p class='Copyright'>
   ファローシャッフルはカードゲームでよく使われている手法で、<br>
   最も実戦的なシャッフル方法です。何度も繰り返すことでカードをよく混ぜることができます。
 </p>
  <div class="show-image">
    <div class="show-image_all">
        <% @farrow_shuffle.each do |libra| %>
          <%= image_tag libra.image, class: "show-image_top" %>
        <% end %>
    </div>
  </div>
  <%= render "shared/footer"%>

app/views/hindus/index.html.erb
<%= render "shared/header" %>
 <br>
 <p class='Copyright'>
   ヒンドゥーシャッフルはデックを右手で下から半数以上持ち上げ、<br>
   左手の束の上に10回重ねる方法を条件としています。これ単体ではあまりカードが混ざらないのがわかります。
 </p>
  <div class="show-image">
    <div class="show-image_all">
        <% @hindu_shuffle.each do |libra| %>
          <%= image_tag libra.image, class: "show-image_top" %>
        <% end %>
    </div>
  </div>
  <%= render "shared/footer"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShuffleMethod4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><a href="/">Shuffle-Inspection</a></h1>
    <%= yield %>
  </body>
</html>

app/views/librarys/index.html.erb
<%= render "shared/header" %>
 <br>
 <p class='Copyright'>
   コンピューターによる完全なランダムシャッフルの結果を表示しています。<br>
   シャッフル結果は理想的で、これを再現するには複数のシャッフル手段を上手に組み合わせる必要があります。
 </p>
 
 <div class="show-image_all">
    <% @library_rundam_all.each do |libra| %>
       <%= image_tag libra.image, class: "show-image_top" %>
    <% end %>
 </div>

  <%= render "shared/footer"%>

app/views/librarys/new.html.erb
<%= render "shared/header" %>

  <%= form_with model: @library, url: librarys_path, local: true do |f|%>

    <div class="container">
      <div class="row">
        <div class="border col-5">

          <br>
          <h1>カード情報登録</h1>
          <br>

            <div class="field">
              <%= f.label :card_type, "カードタイプ", class: "detail__title_form"  %><br />
              <%= f.text_field :card_type, class: :form__text, class: "form-control  btn-dark" %>
            </div>

            <div class="field">
              <%= f.label :numbers, "数値", class: "detail__title_form" %><br />
              <%= f.text_field :numbers, class: :form__text, class: "form-control  btn-dark"%>
            </div>

            <div class="field">
              <%= f.label :image, "カード画像", class: "detail__title_form"  %><br />
              <%= f.file_field :image %>
            </div>

            <div class="actions">
              <%= f.submit "保存する", class: "btn  btn-dark"  %>
            </div>
        </div>
      </div>
    </div>
  <% end %>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <%= render "shared/footer"%>

app/views/opens/index.html.erb
<%= render "shared/header" %>
 <br>
      <p class='Copyright'>
       新品のトランプはこのような順番で並んでいます。ここから色々な方法でシャッフルを試し、<br>
      その効果を検証してみてください。完全ランダムのシャッフルにはどうすれば近づけるでしょうか？
      </p>

    <div class="show-image_all">
        <% @open.each do |libra| %>
          <%= image_tag libra.image, class: "show-image_top" %>
        <% end %>
    </div>


  <%= render "shared/footer"%>

app/views/riffles/index.html.erb
<%= render "shared/header" %>
 <br>
      <p class='Copyright'>
      リフルシャッフルはカードを2つの束に分けて1枚づつ交互に重ねていく手法です。<br>
      今回はそれを2回行なった結果を出しています。開封後のカードを使っているので混ざっていない
      ように見えますが、最もカードを効率よく混ぜることができます。
      
      </p>


      <div class="show-image_all">
        <% @riffle_shuffle.each do |libra| %>
          <%= image_tag libra.image, class: "show-image_top" %>
        <% end %>
      </div>
 <br>
 <br>
 <br>
 <br>
 <br>




  <%= render "shared/footer"%>

app/views/shared/_footer.html.erb
<p class='Copyright'>
 <br>
   Shuffle&Inspectionは新品のトランプを開封した直後に各シャッフル方法の実施結果をシミュレートするツールです。<br>
   ヘッダーからシャッフル方法を選択してください。シャッフルの詳細はその後表示されます。
</p>

app/views/shared/_header.html.erb
<br>
  <div class="container-fluid">
  
    <%= link_to "開封直後の状態(open)", opens_path, class: "link_form" %>
    <%= link_to "完全なシャッフル(Random_shuffle)", librarys_path, class: "link_form" %>
    <%= link_to "ヒンドゥーシャッフル(hindo_shuffle)", hindus_path, class: "link_form" %>
    <%= link_to "リフルシャッフル(riffle_shuffle)", riffles_path, class: "link_form" %>
    <%= link_to "ファローシャッフル(farrow_shuffle)", farrows_path, class: "link_form" %>

  
  
  </div>

app/views/tops/index.html.erb
<%= render "shared/header" %>
 <br>
      <p class='Copyright'>
       Shuffle&Inspectionは新品のトランプを開封した直後に各シャッフル方法の実施結果をシミュレートするツールです。<br>
       ヘッダーからシャッフル方法を選択してください。シャッフルの詳細はその後表示されます。
      </p>
    <br>
    <div class="show-image_root">
        <% @library_rundam_five.each do |libra| %>
          <%= image_tag libra.image, class: "show-image_root" %>
        <% end %>
    </div>
  <br>
  <br>
  <br>
  <%= render "shared/footer"%>